version: "3.8"

services:
    app:
        container_name: indoor_navigation_app
        build:
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./src:/app/src:ro
        env_file:
            - ./.env
        depends_on:
            - mongo
        environment:
            - DB_HOST=mongodb://root:example@mongo:27017/your-database

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_LOG_LEVEL: 1

        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
