services:
    app:
        container_name: indoor_navigation_app
        build:
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./src:/app/src:ro
        env_file:
            - ./.env

