openapi: 3.0.0
info:
    title: Indoor Navigation System
    version: 1.0.0

paths:
    /api/users/signup:
        post:
            summary: Signup
            description: Register a new user.
            tags:
                - Users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                userName:
                                    type: string
                                    example: JohnDoe
                                email:
                                    type: string
                                    example: john.doe@example.com
                                password:
                                    type: string
                                    example: Password@123
                                passwordConfirmation:
                                    type: string
                                    example: Password@123
            responses:
                "201":
                    description: User signed up successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    msg:
                                        type: string
                                        example: User signed up successfully
                                    data:
                                        type: object
                                        properties:
                                            userId:
                                                type: string
                                                example: user123
                                            status:
                                                type: boolean
                                                example: true
                "422":
                    description: Validation error

    /api/users/login:
        post:
            summary: Login
            description: Login and return token.
            tags:
                - Users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                userName:
                                    type: string
                                    example: JohnDoe
                                password:
                                    type: string
                                    example: Password@123
            responses:
                "201":
                    description: User logged in successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    msg:
                                        type: string
                                        example: User logged in
                                    data:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: your_access_token_here
                                            status:
                                                type: boolean
                                                example: true
                "422":
                    description: Validation error

    /api/users/forgetPassword:
        post:
            summary: Forget Password
            description: Send token to user email for confirmation and password reset.
            tags:
                - Users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: john.doe@example.com
            responses:
                "201":
                    description: Password reset token sent successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    msg:
                                        type: string
                                        example: Check your email to reset your password
                                    data:
                                        type: object
                                        properties:
                                            sendMail:
                                                type: boolean
                                                example: true
                                            status:
                                                type: boolean
                                                example: true
                "422":
                    description: Validation error

    /api/users/resetPassword/{resetToken}:
        post:
            summary: Reset Password
            description: Reset password after confirming the token validity.
            tags:
                - Users
            parameters:
                - in: path
                  name: resetToken
                  description: Reset token received from email confirmation
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                password:
                                    type: string
                                    example: Password@123
                                passwordConfirmation:
                                    type: string
                                    example: Password@123
            responses:
                "201":
                    description: User reset password successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    msg:
                                        type: string
                                        example: User reset password successfully
                                    data:
                                        type: object
                                        properties:
                                            status:
                                                type: boolean
                                                example: true
                "422":
                    description: Validation error

    /api/navigate:
        post:
            security:
                - bearerAuth: []
            summary: define user position while movement.
            description: Open bidirectional communication where the user sends the RSSI of surrounding APs so the server can respond with the X,Y coordinates.
            tags:
                - Navigation
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                AP1:
                                    type: integer
                                    description: RSSI value for AP1
                                    example: -70
                                AP2:
                                    type: integer
                                    description: RSSI value for AP2
                                    example: -60
                                AP3:
                                    type: integer
                                    description: RSSI value for AP3
                                    example: -55
            responses:
                "200":
                    description: Bidirectional communication established.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    x:
                                        type: number
                                        description: X coordinate of the user's position
                                    y:
                                        type: number
                                        description: Y coordinate of the user's position
                "404":
                    description: Not found
    /api/navigate/positioning:
        post:
            security:
                - bearerAuth: []
            summary: define user position .
            description: user sends the RSSI of surrounding APs so the server can respond with the X,Y coordinates.
            tags:
                - Navigation
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                AP1:
                                    type: integer
                                    description: RSSI value for AP1
                                    example: -70
                                AP2:
                                    type: integer
                                    description: RSSI value for AP2
                                    example: -60
                                AP3:
                                    type: integer
                                    description: RSSI value for AP3
                                    example: -55
            responses:
                "200":
                    description: response with position of user x,y.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    x:
                                        type: number
                                        description: X coordinate of the user's position
                                    y:
                                        type: number
                                        description: Y coordinate of the user's position
                "404":
                    description: Not found

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
